Metrics/LineLength:
  Max: 100

  # If you want the rule only apply to a specific folder/file
#  Include:
#    - 'app/**/*'

  # If you want the rule not to apply to a specific folder/file
  Exclude:
    - 'db/schema.rb'
